# Generated by Django 3.1.2 on 2021-01-19 23:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('event', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('studies', models.TextField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('intent', models.TextField(blank=True, null=True)),
                ('semester', models.TextField(blank=True, null=True)),
                ('pref_language', models.TextField(blank=True, null=True)),
                ('pref_studies', models.TextField(blank=True, null=True)),
                ('mail_check', models.BooleanField(blank=True, null=True)),
                ('data_check', models.BooleanField(blank=True, null=True)),
                ('participation', models.BooleanField(blank=True, null=True)),
                ('socket', models.TextField(null=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_feedback', through='accounts.Feedback', to='accounts.UserProfile')),
                ('hobbies', models.ManyToManyField(to='accounts.Hobby')),
                ('room', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.room')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First', to='accounts.userprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Second', to='accounts.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_a',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_a', to='accounts.userprofile'),
        ),
        migrations.AddField(
            model_name='feedback',
            name='user_b',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_b', to='accounts.userprofile'),
        ),
    ]
