# Generated by Django 3.1.2 on 2021-01-18 11:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('socket', models.TextField(null=True)),
                ('birthday', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('mail_check', models.BooleanField(blank=True, null=True)),
                ('phone', models.TextField(blank=True, null=True)),
                ('data_check', models.BooleanField(blank=True, null=True)),
                ('studies', models.TextField(blank=True, null=True)),
                ('study_level', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('intent', models.TextField(blank=True, null=True)),
                ('semester', models.TextField(blank=True, null=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
