# Generated by Django 3.1.2 on 2021-01-18 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='participation',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Preference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.TextField(blank=True, null=True)),
                ('studies', models.TextField(blank=True, null=True)),
                ('hobbies', models.ManyToManyField(to='accounts.Hobby')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hobbies',
            field=models.ManyToManyField(blank=True, null=True, to='accounts.Hobby'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='preference',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.preference'),
        ),
    ]
