# Generated by Django 3.1.2 on 2021-01-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210118_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='hobbies',
        ),
        migrations.AddField(
            model_name='hobby',
            name='name',
            field=models.TextField(blank=True, null=True),
        ),
    ]
