# Generated by Django 3.1.2 on 2021-01-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20201212_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDataEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.TextField(blank=True, null=True)),
                ('email', models.TextField(blank=True, null=True)),
                ('first_name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('mail_accept', models.BooleanField(blank=True, null=True)),
                ('mobile_number', models.TextField(blank=True, null=True)),
                ('privacy_accept', models.BooleanField(blank=True, null=True)),
                ('studies', models.TextField(blank=True, null=True)),
                ('study_level', models.TextField(blank=True, null=True)),
                ('university', models.TextField(blank=True, null=True)),
                ('intent', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
