# Generated by Django 3.1.2 on 2021-01-18 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210118_1410'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(blank=True, null=True)),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='First', to='accounts.userprofile')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Second', to='accounts.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='matches',
            field=models.ManyToManyField(related_name='match', through='accounts.Match', to='accounts.UserProfile'),
        ),
    ]
