# Generated by Django 3.1.2 on 2021-01-10 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_userdataentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdataentry',
            name='semester',
            field=models.TextField(blank=True, null=True),
        ),
    ]
