# Generated by Django 3.1.2 on 2021-01-18 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_delete_match'),
        ('accounts', '0004_auto_20210118_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.room'),
        ),
    ]
