# Generated by Django 3.1.2 on 2021-01-19 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_room'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='study_level',
            new_name='status',
        ),
    ]
