# Generated by Django 3.1.2 on 2021-01-18 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_delete_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='meeting_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
