# Generated by Django 3.1.2 on 2021-01-19 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20210118_2117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='link',
            new_name='meetingID',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='meeting_id',
            new_name='moderatorPW',
        ),
        migrations.RemoveField(
            model_name='event',
            name='mod_pw',
        ),
    ]
