# Generated by Django 3.1.2 on 2021-01-19 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_auto_20210119_1609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='link',
            new_name='name',
        ),
    ]
